import React from 'react';

const flights = [
  {
    id: 1,
    airline: 'IndiGo',
    logo: '🔵',
    from: 'Delhi (DEL)',
    to: 'Mumbai (BOM)',
    departure: '06:00 AM',
    arrival: '08:10 AM',
    duration: '2h 10m',
    price: '₹3,499',
    type: 'Non-Stop',
    class: 'Economy',
  },
  {
    id: 2,
    airline: 'Air India',
    logo: '🔴',
    from: 'Bangalore (BLR)',
    to: 'Chennai (MAA)',
    departure: '09:30 AM',
    arrival: '10:45 AM',
    duration: '1h 15m',
    price: '₹2,199',
    type: 'Non-Stop',
    class: 'Business',
  },
  {
    id: 3,
    airline: 'SpiceJet',
    logo: '🟠',
    from: 'Hyderabad (HYD)',
    to: 'Kolkata (CCU)',
    departure: '11:00 AM',
    arrival: '01:20 PM',
    duration: '2h 20m',
    price: '₹4,799',
    type: 'Non-Stop',
    class: 'Economy',
  },
  {
    id: 4,
    airline: 'Vistara',
    logo: '🟣',
    from: 'Mumbai (BOM)',
    to: 'Goa (GOI)',
    departure: '02:15 PM',
    arrival: '03:30 PM',
    duration: '1h 15m',
    price: '₹5,299',
    type: 'Non-Stop',
    class: 'Business',
  },
  {
    id: 5,
    airline: 'GoFirst',
    logo: '🟢',
    from: 'Delhi (DEL)',
    to: 'Jaipur (JAI)',
    departure: '05:45 PM',
    arrival: '06:45 PM',
    duration: '1h 00m',
    price: '₹1,899',
    type: 'Non-Stop',
    class: 'Economy',
  },
  {
    id: 6,
    airline: 'Akasa Air',
    logo: '🟡',
    from: 'Pune (PNQ)',
    to: 'Delhi (DEL)',
    departure: '07:30 PM',
    arrival: '09:40 PM',
    duration: '2h 10m',
    price: '₹3,999',
    type: 'Non-Stop',
    class: 'Economy',
  },
];

export { flights };
export default flights;
